### ISSUE TITLE
Can the size template parameter 'N' be made into a variable?

### ISSUE THREAD

**Issue by randomizedthinking** [JustasMasiulis/circular_buffer#8]
First, thanks for the nice package.

My request is whether the template parameter `N` be made into a variable rather a constant? I have use cases that the size of the buffer is unknown, and is set in a configuration file. It is one less constraint for the circular buffer class. Let me know how you think.

**Comment by JustasMasiulis** [comment]
Nope. This library was made with having a static buffer in mind. Changing this would quite a bit of work and since this is a really old lib I personally don't use anymore I don't think I'll ever be doing this.

**Comment by randomizedthinking** [comment]
No problem... understand.
