### ISSUE TITLE
Explanation: What returns pop_front after producer exceeds ringbuffer size ?

### ISSUE THREAD

**Issue by lumpidu** [JustasMasiulis/circular_buffer#9]
The documentation is not overly verbose.

I cannot read, what is returned via `pop_front()` after the ring buffer producer has already overwritten the current reading position element. Is the reading position moved as well ? Could you explain ?

**Comment by JustasMasiulis** [comment]
Yes. When you overfill the buffer the head/front of it moves forward as well.

**Comment by lumpidu** [comment]
Thx for clarification. Closing.
